/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: dinomaster (https://sketchfab.com/dinomaster)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/my-animated-ho-oh-62ad7114edb9446cb3848b43eafb9cf5
title: my animated ho-oh
*/

import React, { useEffect, useRef, FC } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { AnimationClip, Material, Mesh, Object3D } from "three";
import { pathname } from "src/datas/navbar";

export const Hooh3D: FC = (props: any) => {
  const group = useRef<Mesh>(null!);

  const { nodes, materials, animations }: any = useGLTF(`${pathname}hooh.glb`);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions["Take 001"]!.play();
  }, []);

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      position={[0, -0.3, 0]}
      scale={[0.017, 0.017, 0.017]}
    >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, -0.5]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Sketchfab_model_0" rotation={[-Math.PI / 2, 0, 0]}>
                <group name="root_1">
                  <group
                    name="GLTF_SceneRootNode_2"
                    rotation={[Math.PI / 2, 0, 0]}
                  >
                    <group name="GLTF_created_0_3">
                      <group name="GLTF_created_0">
                        <primitive object={nodes.GLTF_created_0_rootJoint} />
                        <group name="Object_7_7_correction">
                          <group name="Object_7_7" />
                        </group>
                        <group name="Object_9_9_correction">
                          <group name="Object_9_9" />
                        </group>
                        <group name="Object_11_11_correction">
                          <group name="Object_11_11" />
                        </group>
                        <group name="Object_13_13_correction">
                          <group name="Object_13_13" />
                        </group>
                        <skinnedMesh
                          name="Object_176"
                          geometry={nodes.Object_176.geometry}
                          material={materials.material_0}
                          skeleton={nodes.Object_176.skeleton}
                        />
                        <skinnedMesh
                          name="Object_179"
                          geometry={nodes.Object_179.geometry}
                          material={materials.material_1}
                          skeleton={nodes.Object_179.skeleton}
                        />
                        <skinnedMesh
                          name="Object_182"
                          geometry={nodes.Object_182.geometry}
                          material={materials.material_2}
                          skeleton={nodes.Object_182.skeleton}
                        />
                        <skinnedMesh
                          name="Object_185"
                          geometry={nodes.Object_185.geometry}
                          material={materials.material_3}
                          skeleton={nodes.Object_185.skeleton}
                        />
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/hooh.glb");
